### ISSUE TITLE
The Big Release Post

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/bigdatagenomics.github.io#17]
Release All The Tools!

- [ ] High-bit about variant calling with Cannoli/ADAM/Avocado
- [x] Exposing Spark SQL in ADAM
- [x] Python and R APIs (including pip installability)
- [ ] Performance evaluation vs GATK4
- [x] Upcoming Mango release (I presume this is OK for us to mention? @akmorrow13)
- [x] Documentation move to readthedocs
- [ ] General ADAM release tidbits
- [x] Dropping Spark 1.x, Scala 2.10 support

**Comment by heuermh** [comment]
Should mention dropping Spark 1.x in the next release.

**Comment by heuermh** [comment]
Fixed by commit f6d4fc0d0616585eea5662901f460a98243a3da4
